version: '2'

#https://hub.docker.com/r/bitnami/postgresql
services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postpost
      - POSTGRESQL_DATABASE=my_database

volumes:
  postgresql_data:
    driver: local