# https://hub.docker.com/r/niiknow/vestacp/
# Login: admin Password: MakeItSo18

# Start:
#mkdir -p /opt/vestacp/{vesta,home,backup}
# docker run -d --restart=always -p 2222:22 -p 80:80 -p 443:443 -p 3306:3306 -p 5432:5432 -p 8083:8083 -v /opt/vestacp/vesta:/vesta -v /opt/vestacp/home:/home -v /opt/vestacp/backup:/backup niiknow/vestacp

FROM niiknow/vestacp
