version: "2.0"
services:
  webphp5:
    build: apache-php56/.
    container_name: alpine_apache_php5.6
    hostname: php5
    #image: gotechnies/php-5.6-alpine
    ports:
       - "25080:80"
       - "25443:443"
    volumes:
      - /docker/web/html:/var/www/html
    restart: always
    network_mode: 'bridge'
    links: 
      - 'mysql'
  webphp7:
    build: apache-php7/.
    container_name: alpine_apache_php7
    hostname: php7
    ports:
       - "27080:80"
       - "27443:443"
    volumes:
      - /docker/web/html:/var/www/html
    restart: always
    network_mode: 'bridge'
    links: 
      - 'mysql'
  mysql:
    build: mysql/.
    #image: 'pluie/alpine-mysql'
    container_name: alpine_mariadb
    hostname: mysql
    environment:
      - MYSQL_DATABASE=mybase         # create specified database at startup
      - MYSQL_USER=my_user            # create specified user at startup (and grant all rights to MYSQL_DATABASE)
      - MYSQL_PASSWORD=my_password
      - MYSQL_ROOT_PASSWORD=senhasenha
      - TZ=America/Sao_Paulo
      - SHENV_CTX=LOCAL     # LOCAL|INT|PROD change context bg color
      - SHENV_NAME=Mysql    # container name 
      - SHENV_COLOR=97      # ANSI EXTENDED COLOR CODEl
    volumes:
      #- '/home/docker/mysql/bancodedados:/var/lib/mysql'
      - '/home/docker/mysql/dump:/dump'
      - '/home/docker/mysql/app:/app'
    ports:
      - 3306:3306
    network_mode: 'bridge'
    restart: always
  phpmyadmin:
    #image: phpmyadmin/phpmyadmin
    build: phpmyadmin/.
    container_name: alpine_phpmyadmin
    hostname: phpmyadmin
    environment:
     - PMA_ARBITRARY=1
    restart: always
    ports:
     - 8080:80
    volumes:
     - /sessions
    network_mode: 'bridge'
    links: 
      - 'mysql'    
  adminer:
    #image: adminer
    build: adminer/.
    container_name: alpine_adminer
    hostname: adminer
    ports:
      - 18080:8080
    environment:
      - ADMINER_PLUGINS=
    restart: always
    network_mode: 'bridge'
    links: 
      - 'mysql'
    #tty: true
    #stdin_open: true
    #privileged: true
    #user: root

#Note-: If you want to restart the docker container on system start up, uncomment the restart:always line.
