version: '2'
services: 
  xampp56:
    build: ./.
    container_name: xampp_56
    hostname: xampp_56
    dns:
      - localhost
      - 1.1.1.1
    ports:
      - '40022:22'
      - '40080:80'
      - '43306:3306'
    network_mode: bridge
    volumes:
      - /home/docker/mysql/xampp56:/opt/lampp/var/mysql
      - /home/docker/logs:/opt/lampp/logs
      - /home/docker/tools:/tools
      - /home/docker/web:/web
      - /home/docker/xamp_56/etc:/opt/lampp/etc
    restart: always
    tty: true
    stdin_open: true
    privileged: true
    #user: www-data